#!/usr/bin/perl -w

use strict;
use DR;

for my $r1 (qw(p q r s)) {
	for my $r2 (qw(p q r s t u v w)) {
		next if $r2 eq $r1;
		for my $r3 (qw(p q r s t u v w)) {
			next if $r3 eq $r1 or $r3 eq $r2;
			perm($r1, $r2, $r3, uc($r2), uc($r3), uc($r1));
			perm($r1, uc($r2), $r3, $r2, uc($r3), uc($r1));
			perm($r1, $r2, uc($r3), uc($r2), $r3, uc($r1));
			perm($r1, uc($r2), uc($r3), $r2, $r3, uc($r1));
		}
	}
}
showres;
